### ISSUE TITLE
看到有个库 fork 了你的代码，然后单独发了包和版本，是一起维护的不

### ISSUE THREAD

**Issue by bigmeow** [vivaxy/WXML#30]
看到有个库 fork 了你的代码，然后单独发了包和版本，是一起维护的不，还是后面打算迁移到那个库了，从包名来说 `wxml` 的确比 `@vivaxy/WXML` 更好
https://github.com/oft/wxml

**Comment by vivaxy** [comment]
目前不是一起维护的。看到那个包确实有些不同：

1. 对单双引号的处理不同
2. 增加了列信息，更友好的报错

麻烦 @oft 看下是否后续可以统一交给你这边维护？

**Comment by vivaxy** [comment]
@bigmeow 本仓库关闭，wxml 相关在 https://github.com/oft/wxml 仓库维护。
